kind: Deployment
apiVersion: apps/v1
metadata:
  name: fazowicz
  namespace: fazowicz
  labels:
    app: fazowicz
spec:
  selector:
    matchLabels:
      app: fazowicz
  template:
    metadata:
      labels:
        app: fazowicz
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: fazowicz
          image: ???
          env:
            - name: LOG_PATH
              value: /var/lib/fazowicz/fazowicz.log
            - name: FAZOWICZ_CONFIG
              value: /var/lib/fazowicz/fazowicz_config.json
            - name: TZ
              value: Europe/Warsaw
          # resources:
          #   limits:
          #     cpu: "0.5"
          #     memory: 384Mi
          volumeMounts:
            - mountPath: /opt/fazowicz/token
              name: fazowicz-sec
              subPath: token
            - mountPath: /var/lib/fazowicz
              name: fazowicz-pvc
            - mountPath: /tmp
              name: temp
      volumes:
        - name: fazowicz-sec
          secret:
            secretName: fazowicz-sec
        - name: fazowicz-pvc
          persistentVolumeClaim:
            claimName: fazowicz-pvc
        - name: temp
          emptyDir: {}
      initContainers:
        - name: volume-ownership
          image: alpine
          volumeMounts:
            - mountPath: /var/lib/fazowicz
              name: fazowicz-pvc
          command:
            - "sh"
            - "-c"
            - |
              chown -v 999:999 /var/lib/fazowicz