kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fazowicz-pvc
  namespace: fazowicz
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cinder-classic